//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute("Gibbed.TombRaider.FileFormats")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Release")]
[assembly: System.Reflection.AssemblyCopyrightAttribute("Copyright © Gibbed 2011")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("8.0.18.1278")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("8.0.18.1278+1ee129b814c933ccd7fd53eecfabec893e885e19")]
[assembly: System.Reflection.AssemblyProductAttribute("Gibbed.TombRaider.FileFormats")]
[assembly: System.Reflection.AssemblyTitleAttribute("Gibbed.TombRaider.FileFormats")]
[assembly: System.Reflection.AssemblyVersionAttribute("8.0.18.1278")]

// Generated by the MSBuild WriteCodeFragment class.

