//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute("Novell")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Release")]
[assembly: System.Reflection.AssemblyCopyrightAttribute("Copyright © Novell 2008")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("9.0.30729.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("9.0.30729+1ee129b814c933ccd7fd53eecfabec893e885e19")]
[assembly: System.Reflection.AssemblyProductAttribute("NDesk.Options")]
[assembly: System.Reflection.AssemblyTitleAttribute("NDesk.Options")]
[assembly: System.Reflection.AssemblyVersionAttribute("9.0.30729.0")]

// Generated by the MSBuild WriteCodeFragment class.

