//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute("Gibbed.TombRaider.RebuildFileLists")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyCopyrightAttribute("Copyright © Gibbed 2011")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("8.0.23.1149")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("8.0.23.1149-Development+71a23c76312bc612d7d108d5e44203794dee9812")]
[assembly: System.Reflection.AssemblyProductAttribute("Gibbed.TombRaider")]
[assembly: System.Reflection.AssemblyTitleAttribute("Gibbed.TombRaider.RebuildFileLists")]
[assembly: System.Reflection.AssemblyVersionAttribute("8.0.23.1149")]

// Generated by the MSBuild WriteCodeFragment class.

